---
- when: "database_name is not defined"
  name: "calculate database name"
  set_fact: "database_name={{ app_name }}_prod"


- name: "create or get postgres password"
  set_fact: database_password="{{ database_password_secret }}"

- name: "set database user"
  set_fact: database_user="{{ deployer }}"
